---
title: Myst1cS04p
baseurl: "/Me"
url: "https://myst1cs04p.github.io"
markdown: kramdown
theme: null
username: Myst1cS04p
tagline: DEVELOPER | SYSTEMS THINKER | PROTOTYPE ALCHEMIST

collections:
  projects:
    output: true
    permalink: /projects/:name
  articles:
    output: true
    permalink: /posts/:name